#lang pollen/pre

◊(require racket/match
          "profile.rkt")

◊(define (project-lines items)
   (apply string-append
          (for/list ([item (in-list items)])
            (match item
              [(cons name description)
               (format "- `~a`: ~a\n" name description)]))))

# ◊(field 'name)

◊(field 'tagline)

- website: <◊(field 'website)>
- workshop: ◊(workshop-line)
- now: ◊(current-line)

## current map

◊(project-lines projects)

<!-- generated by README.md.pp; run: raco pollen render README.md.pp -->
