#lang racket

(require racket/match)

(define profile
  '((name . "mayphus")
    (tagline . "maker of software, hardware, mechanical, and occasional chaos.")
    (website . "https://mayphus.org/")
    (workshop . ("emacs"
                 "cloudflare workers"
                 "tiny computers"
                 "small scripts that became projects"))
    (status . "building things at the edges where domains collide")))

(define (field key)
  (match (assoc key profile)
    [(cons _ value) value]
    [#f (error 'field "missing profile field: ~a" key)]))

(define (markdown-link url)
  (format "<~a>" url))

(define (english-list items)
  (match items
    ['() ""]
    [(list one) one]
    [(list one two) (format "~a and ~a" one two)]
    [_ (format "~a, and ~a"
               (string-join (drop-right items 1) ", ")
               (last items))]))

(define (workshop-line items)
  (format "currently somewhere between ~a"
          (english-list items)))

(define readme
  (string-append
   (format "# ~a\n\n" (field 'name))
   (format "~a\n\n" (field 'tagline))
   (format "- website: ~a\n" (markdown-link (field 'website)))
   (format "- workshop: ~a\n" (workshop-line (field 'workshop)))
   (format "- status: ~a\n" (field 'status))
   "\n"
   "<!-- generated by readme.rkt; run: racket readme.rkt -->\n"))

(module+ main
  (call-with-output-file "README.md"
    #:exists 'replace
    (lambda (out)
      (display readme out))))
